using System;
using System.Globalization;
using System.IO;
using System.Text;
using LibRender;
using OpenBveApi.Graphics;
using OpenBveApi.Objects;
using OpenBveApi.Packages;
using SoundManager;
using Path = OpenBveApi.Path;

namespace OpenBve
{
	internal partial class Interface
	{
		/// <summary>Defines the possible timetable display modes</summary>
		internal enum TimeTableMode
		{
			/// <summary>Timetable display is disabled</summary>
			None = 0,
			/// <summary>The custom timetable (if set) will be displayed first, followed by the auto-generated timetable</summary>
			Default = 1,
			/// <summary>Only the auto-generated timetable will be displayed</summary>
			AutoGenerated = 2,
			/// <summary>The auto-generated timetable will be displayed only if no custom timetable is available</summary>
			PreferCustom = 3
		}
		internal enum GameMode
		{
			Arcade = 0,
			Normal = 1,
			Expert = 2
		}

		internal class Options
		{
			/// <summary>The ISO 639-1 code for the current user interface language</summary>
			internal string LanguageCode;
			/// <summary>Whether the program is to be run in full-screen mode</summary>
			internal bool FullscreenMode;
			/// <summary>Whether the program is to be rendered using vertical syncronisation</summary>
			internal bool VerticalSynchronization;
			/// <summary>The screen width (Windowed Mode)</summary>
			internal int WindowWidth;
			/// <summary>The screen height (Windowed Mode)</summary>
			internal int WindowHeight;
			/// <summary>The screen width (Fullscreen Mode)</summary>
			internal int FullscreenWidth;
			/// <summary>The screen height (Fullscreen Mode)</summary>
			internal int FullscreenHeight;
			/// <summary>The number of bits per pixel (Only relevant in fullscreen mode)</summary>
			internal int FullscreenBits;
			/// <summary>The on disk folder in which user interface components are stored</summary>
			internal string UserInterfaceFolder;
			/// <summary>The current pixel interpolation mode </summary>
			internal InterpolationMode Interpolation;
			/// <summary>The current transparency quality mode</summary>
			internal TransparencyMode TransparencyMode;
			/// <summary>The level of anisotropic filtering to be applied</summary>
			internal int AnisotropicFilteringLevel;
			/// <summary>The maximum level of anisotropic filtering supported by the system</summary>
			internal int AnisotropicFilteringMaximum;
			/// <summary>The accelerated time factor (1x to 5x)</summary>
			internal int TimeAccelerationFactor;
			/// <summary>The level of antialiasing to be applied</summary>
			internal int AntiAliasingLevel;
			/// <summary>The viewing distance in meters</summary>
			internal int ViewingDistance;
			/// <summary>The current type of motion blur</summary>
			internal MotionBlurMode MotionBlur;
			/*
			 * Note: Object optimisation takes time whilst loading, but may increase the render performance of an
			 * object by checking for duplicate vertices etc.
			 */
			/// <summary>The minimum number of vertices for basic optimisation to be performed on an object</summary>
			internal int ObjectOptimizationBasicThreshold;
			/// <summary>The minimum number of verticies for full optimisation to be performed on an object</summary>
			internal int ObjectOptimizationFullThreshold;
			/// <summary>Whether duplicate verticies are culled during loading</summary>
			internal bool ObjectOptimizationVertexCulling;
			/// <summary>Whether toppling is enabled</summary>
			internal bool Toppling;
			/// <summary>Whether collisions between trains are enabled</summary>
			internal bool Collisions;
			/// <summary>Whether derailments are enabled</summary>
			internal bool Derailments;
			/// <summary>Whether loading sway is added</summary>
			internal bool LoadingSway;
			/// <summary>Whether the black-box data logger is enabled</summary>
			internal bool BlackBox;
			/// <summary>Whether joystick support is enabled</summary>
			internal bool UseJoysticks;
			/// <summary>The threshold below which joystick axis motion will be disregarded</summary>
			internal double JoystickAxisThreshold;
			/// <summary>The delay after which a held-down key will start to repeat</summary>
			internal double KeyRepeatDelay;
			/// <summary>The interval at which a held down key will repeat after the intial delay</summary>
			internal double KeyRepeatInterval;
			/// <summary>The current sound model</summary>
			internal SoundsBase.SoundModels SoundModel;
			/// <summary>The range outside of which sounds will be inaudible</summary>
			internal SoundsBase.SoundRange SoundRange;
			/// <summary>The maximum number of sounds playing at any one time</summary>
			internal int SoundNumber;
			/// <summary>Whether warning messages are to be shown</summary>
			internal bool ShowWarningMessages;
			/// <summary>Whether error messages are to be shown</summary>
			internal bool ShowErrorMessages;
			/// <summary>The current route's on-disk folder path</summary>
			internal string RouteFolder;
			/// <summary>The current train's on-disk folder path</summary>
			internal string TrainFolder;
			/// <summary>The list of recently used routes</summary>
			internal string[] RecentlyUsedRoutes;
			/// <summary>The list of recently used trains</summary>
			internal string[] RecentlyUsedTrains;
			/// <summary>The maximum number of recently used routes/ trains to display</summary>
			internal readonly int RecentlyUsedLimit;
			/// <summary>The list of recently used route character encodings</summary>
			internal TextEncoding.EncodingValue[] RouteEncodings;
			/// <summary>The list of recently used train character encodings</summary>
			internal TextEncoding.EncodingValue[] TrainEncodings;
			/// <summary>The game mode- Affects how the score is calculated</summary>
			internal GameMode GameMode;
			/// <summary>The width of the main menu window</summary>
			internal int MainMenuWidth;
			/// <summary>The height of the main menu window</summary>
			internal int MainMenuHeight;
			/// <summary>Whether the use of OpenGL display lists is disabled</summary>
			internal bool DisableDisplayLists;
			/// <summary>Whether the simulation will load all textures and sounds into system memory on initial load</summary>
			internal bool LoadInAdvance;
			/// <summary>Whether the simulation will dynamically unload unused textures</summary>
			internal bool UnloadUnusedTextures;
			/// <summary>Whether EB application is possible from the use of a joystick axis</summary>
			internal bool AllowAxisEB;
			/// <summary>Whether to prefer the native OpenTK operating system backend</summary>
			internal bool PreferNativeBackend = true;
			/// <summary>Stores whether the RailDriver speed display is in MPH (true) or KPH (false)</summary>
			internal bool RailDriverMPH;
			/// <summary>Enables / disables various hacks for BVE related content</summary>
			internal bool EnableBveTsHacks;
			/// <summary>Stores whether to use fuzzy matching for transparency colors (Matches BVE2 / BVE4 behaviour)</summary>
			internal bool OldTransparencyMode;
			/// <summary>The list of enable Input Device Plugins</summary>
			internal string[] EnableInputDevicePlugins;

			internal string CursorFileName;
			internal bool Panel2ExtendedMode;
			internal int Panel2ExtendedMinSize;

			internal XParsers CurrentXParser;
			internal ObjParsers CurrentObjParser;

			internal TimeTableMode TimeTableStyle;

			internal CompressionType packageCompressionType;
			/*
			 * Only relevant in developer mode, not saved
			 */
			internal bool ShowEvents = false;

			/// <summary>Whether we are currently in kiosk mode</summary>
			internal bool KioskMode;
			/// <summary>The timer before AI controls are enabled in kiosk mode</summary>
			internal double KioskModeTimer; //5 minutes by default set in ctor
											/*
											 * Note: The following options were (are) used by the Managed Content system, and are currently non-functional
											 */
											/// <summary>The proxy URL to use when retrieving content from the internet</summary>
			internal string ProxyUrl;
			/// <summary>The proxy username to use when retrieving content from the internet</summary>
			internal string ProxyUserName;
			/// <summary>The proxy password to use when retrieving content from the internet</summary>
			internal string ProxyPassword;
			/// <summary>Creates a new instance of the options class with default values set</summary>
			internal Options()
			{
				LanguageCode = "en-US";
				FullscreenMode = false;
				VerticalSynchronization = true;
				WindowWidth = 960;
				WindowHeight = 600;
				FullscreenWidth = 1024;
				FullscreenHeight = 768;
				FullscreenBits = 32;
				UserInterfaceFolder = "Default";
				Interpolation = InterpolationMode.BilinearMipmapped;
				TransparencyMode = TransparencyMode.Quality;
				AnisotropicFilteringLevel = 0;
				AnisotropicFilteringMaximum = 0;
				AntiAliasingLevel = 0;
				ViewingDistance = 600;
				MotionBlur = MotionBlurMode.None;
				Toppling = true;
				Collisions = true;
				Derailments = true;
				LoadingSway = false;
				GameMode = GameMode.Normal;
				BlackBox = false;
				UseJoysticks = true;
				JoystickAxisThreshold = 0.0;
				KeyRepeatDelay = 0.5;
				KeyRepeatInterval = 0.1;
				SoundModel = SoundsBase.SoundModels.Inverse;
				SoundRange = SoundsBase.SoundRange.Low;
				SoundNumber = 16;
				ShowWarningMessages = true;
				ShowErrorMessages = true;
				ObjectOptimizationBasicThreshold = 10000;
				ObjectOptimizationFullThreshold = 1000;
				ObjectOptimizationVertexCulling = false;
				RouteFolder = "";
				TrainFolder = "";
				RecentlyUsedRoutes = new string[] { };
				RecentlyUsedTrains = new string[] { };
				RecentlyUsedLimit = 10;
				RouteEncodings = new TextEncoding.EncodingValue[] { };
				TrainEncodings = new TextEncoding.EncodingValue[] { };
				MainMenuWidth = 0;
				MainMenuHeight = 0;
				DisableDisplayLists = false;
				LoadInAdvance = false;
				UnloadUnusedTextures = false;
				ProxyUrl = string.Empty;
				ProxyUserName = string.Empty;
				ProxyPassword = string.Empty;
				TimeAccelerationFactor = 5;
				AllowAxisEB = true;
				TimeTableStyle = TimeTableMode.Default;
				packageCompressionType = CompressionType.Zip;
				RailDriverMPH = true;
				EnableBveTsHacks = true;
				OldTransparencyMode = true;
				KioskMode = false;
				KioskModeTimer = 300;
				EnableInputDevicePlugins = new string[] { };
				CursorFileName = "nk.png";
				Panel2ExtendedMode = false;
				Panel2ExtendedMinSize = 128;
				CurrentXParser = XParsers.Original; //Set to Michelle's original X parser by default
				CurrentObjParser = ObjParsers.Original; //Set to original Obj parser by default
			}
		}
		/// <summary>The current game options</summary>
		internal static Options CurrentOptions;
		/// <summary>Loads the options file from disk</summary>
		internal static void LoadOptions()
		{
			string OptionsDir = Path.CombineDirectory(Program.FileSystem.SettingsFolder, "1.5.0");
			if (!Directory.Exists(OptionsDir))
			{
				Directory.CreateDirectory(OptionsDir);
			}
			CurrentOptions = new Options();
			CultureInfo Culture = CultureInfo.InvariantCulture;
			string File = Path.CombineFile(OptionsDir, "options.cfg");
			if (!System.IO.File.Exists(File))
			{
				//Attempt to load and upgrade a prior configuration file
				File = Path.CombineFile(Program.FileSystem.SettingsFolder, "options.cfg");
			}
			if (System.IO.File.Exists(File))
			{
				// load options
				string[] Lines = System.IO.File.ReadAllLines(File, new UTF8Encoding());
				string Section = "";
				for (int i = 0; i < Lines.Length; i++)
				{
					Lines[i] = Lines[i].Trim();
					if (Lines[i].Length != 0 && !Lines[i].StartsWith(";", StringComparison.OrdinalIgnoreCase))
					{
						if (Lines[i].StartsWith("[", StringComparison.Ordinal) & Lines[i].EndsWith("]", StringComparison.Ordinal))
						{
							Section = Lines[i].Substring(1, Lines[i].Length - 2).Trim().ToLowerInvariant();
						}
						else
						{
							int j = Lines[i].IndexOf("=", StringComparison.OrdinalIgnoreCase);
							string Key, Value;
							if (j >= 0)
							{
								Key = Lines[i].Substring(0, j).TrimEnd().ToLowerInvariant();
								Value = Lines[i].Substring(j + 1).TrimStart();
							}
							else
							{
								Key = "";
								Value = Lines[i];
							}
							switch (Section)
							{
								case "language":
									switch (Key)
									{
										case "code":
											CurrentOptions.LanguageCode = Value.Length != 0 ? Value : "en-US";
											break;
									}
									break;
								case "interface":
									switch (Key)
									{
										case "folder":
											CurrentOptions.UserInterfaceFolder = Value.Length != 0 ? Value : "Default";
											break;
										case "timetablemode":
											switch (Value.ToLowerInvariant())
											{
												case "none":
													CurrentOptions.TimeTableStyle = TimeTableMode.None;
													break;
												case "default":
													CurrentOptions.TimeTableStyle = TimeTableMode.Default;
													break;
												case "autogenerated":
													CurrentOptions.TimeTableStyle = TimeTableMode.AutoGenerated;
													break;
												case "prefercustom":
													CurrentOptions.TimeTableStyle = TimeTableMode.PreferCustom;
													break;
											}
											break;
										case "kioskmode":
											CurrentOptions.KioskMode = string.Compare(Value, "true", StringComparison.OrdinalIgnoreCase) == 0;
											break;
										case "kioskmodetimer":
											double d;
											if (!double.TryParse(Value, NumberStyles.Number, Culture, out d))
											{
												d = 300;
											}
											if (d > 1000 || d < 0)
											{
												d = 300;
											}
											CurrentOptions.KioskModeTimer = d;
											break;
									}
									break;
								case "display":
									switch (Key)
									{
										case "prefernativebackend":
											CurrentOptions.PreferNativeBackend = string.Compare(Value, "true", StringComparison.OrdinalIgnoreCase) == 0;
											break;
										case "mode":
											CurrentOptions.FullscreenMode = string.Compare(Value, "fullscreen", StringComparison.OrdinalIgnoreCase) == 0;
											break;
										case "vsync":
											CurrentOptions.VerticalSynchronization = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "windowwidth":
											{
												int a;
												if (!int.TryParse(Value, NumberStyles.Integer, Culture, out a))
												{
													a = 960;
												}
												CurrentOptions.WindowWidth = a;
											}
											break;
										case "windowheight":
											{
												int a;
												if (!int.TryParse(Value, NumberStyles.Integer, Culture, out a))
												{
													a = 600;
												}
												CurrentOptions.WindowHeight = a;
											}
											break;
										case "fullscreenwidth":
											{
												int a;
												if (!int.TryParse(Value, NumberStyles.Integer, Culture, out a))
												{
													a = 1024;
												}
												CurrentOptions.FullscreenWidth = a;
											}
											break;
										case "fullscreenheight":
											{
												int a;
												if (!int.TryParse(Value, NumberStyles.Integer, Culture, out a))
												{
													a = 768;
												}
												CurrentOptions.FullscreenHeight = a;
											}
											break;
										case "fullscreenbits":
											{
												int a;
												if (!int.TryParse(Value, NumberStyles.Integer, Culture, out a))
												{
													a = 32;
												}
												CurrentOptions.FullscreenBits = a;
											}
											break;
										case "mainmenuwidth":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												CurrentOptions.MainMenuWidth = a;
											}
											break;
										case "mainmenuheight":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												CurrentOptions.MainMenuHeight = a;
											}
											break;
										case "disabledisplaylists":
											CurrentOptions.DisableDisplayLists = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "loadinadvance":
											CurrentOptions.LoadInAdvance = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "unloadtextures":
											CurrentOptions.UnloadUnusedTextures = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
									}
									break;
								case "quality":
									switch (Key)
									{
										case "interpolation":
											switch (Value.ToLowerInvariant())
											{
												case "nearestneighbor": CurrentOptions.Interpolation = InterpolationMode.NearestNeighbor; break;
												case "bilinear": CurrentOptions.Interpolation = InterpolationMode.Bilinear; break;
												case "nearestneighbormipmapped": CurrentOptions.Interpolation = InterpolationMode.NearestNeighborMipmapped; break;
												case "bilinearmipmapped": CurrentOptions.Interpolation = InterpolationMode.BilinearMipmapped; break;
												case "trilinearmipmapped": CurrentOptions.Interpolation = InterpolationMode.TrilinearMipmapped; break;
												case "anisotropicfiltering": CurrentOptions.Interpolation = InterpolationMode.AnisotropicFiltering; break;
												default: CurrentOptions.Interpolation = InterpolationMode.BilinearMipmapped; break;
											}
											break;
										case "anisotropicfilteringlevel":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												CurrentOptions.AnisotropicFilteringLevel = a;
											}
											break;
										case "anisotropicfilteringmaximum":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												CurrentOptions.AnisotropicFilteringMaximum = a;
											}
											break;
										case "antialiasinglevel":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												CurrentOptions.AntiAliasingLevel = a;
											}
											break;
										case "transparencymode":
											switch (Value.ToLowerInvariant())
											{
												case "sharp": CurrentOptions.TransparencyMode = TransparencyMode.Performance; break;
												case "smooth": CurrentOptions.TransparencyMode = TransparencyMode.Quality; break;
												default:
													{
														int a;
														if (int.TryParse(Value, NumberStyles.Integer, Culture, out a))
														{
															CurrentOptions.TransparencyMode = (TransparencyMode)a;
														}
														else
														{
															CurrentOptions.TransparencyMode = TransparencyMode.Quality;
														}
														break;
													}
											}
											break;
										case "oldtransparencymode":
											CurrentOptions.OldTransparencyMode = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "viewingdistance":
											{
												int a;
												if (int.TryParse(Value, NumberStyles.Integer, Culture, out a))
												{
													if (a >= 100 && a <= 10000)
													{
														CurrentOptions.ViewingDistance = a;
													}
												}
											}
											break;
										case "motionblur":
											switch (Value.ToLowerInvariant())
											{
												case "low": CurrentOptions.MotionBlur = MotionBlurMode.Low; break;
												case "medium": CurrentOptions.MotionBlur = MotionBlurMode.Medium; break;
												case "high": CurrentOptions.MotionBlur = MotionBlurMode.High; break;
												default: CurrentOptions.MotionBlur = MotionBlurMode.None; break;
											}
											break;
									}
									break;
								case "objectoptimization":
									switch (Key)
									{
										case "basicthreshold":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												CurrentOptions.ObjectOptimizationBasicThreshold = a;
											}
											break;
										case "fullthreshold":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												CurrentOptions.ObjectOptimizationFullThreshold = a;
											}
											break;
										case "vertexCulling":
											{
												CurrentOptions.ObjectOptimizationVertexCulling = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											}
											break;
									}
									break;
								case "simulation":
									switch (Key)
									{
										case "toppling":
											CurrentOptions.Toppling = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "collisions":
											CurrentOptions.Collisions = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "derailments":
											CurrentOptions.Derailments = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "loadingsway":
											CurrentOptions.LoadingSway = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "blackbox":
											CurrentOptions.BlackBox = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "mode":
											switch (Value.ToLowerInvariant())
											{
												case "arcade": CurrentOptions.GameMode = GameMode.Arcade; break;
												case "normal": CurrentOptions.GameMode = GameMode.Normal; break;
												case "expert": CurrentOptions.GameMode = GameMode.Expert; break;
												default: CurrentOptions.GameMode = GameMode.Normal; break;
											}
											break;
										case "acceleratedtimefactor":
											int tf;
											int.TryParse(Value, NumberStyles.Integer, Culture, out tf);
											if (tf <= 0)
											{
												tf = 5;
											}
											CurrentOptions.TimeAccelerationFactor = tf;
											break;
										case "enablebvetshacks":
											CurrentOptions.EnableBveTsHacks = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;

									}
									break;
								case "controls":
									switch (Key)
									{
										case "usejoysticks":
											CurrentOptions.UseJoysticks = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "joystickaxiseb":
											CurrentOptions.AllowAxisEB = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "joystickaxisthreshold":
											{
												double a;
												double.TryParse(Value, NumberStyles.Float, Culture, out a);
												CurrentOptions.JoystickAxisThreshold = a;
											}
											break;
										case "keyrepeatdelay":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												if (a <= 0)
												{
													a = 500;
												}

												CurrentOptions.KeyRepeatDelay = 0.001 * a;
											}
											break;
										case "keyrepeatinterval":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												if (a <= 0)
												{
													a = 100;
												}

												CurrentOptions.KeyRepeatInterval = 0.001 * a;
											}
											break;
										case "raildrivermph":
											CurrentOptions.RailDriverMPH = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
									}
									break;
								case "sound":
									switch (Key)
									{
										case "model":
											switch (Value.ToLowerInvariant())
											{
												case "linear": CurrentOptions.SoundModel = SoundsBase.SoundModels.Linear; break;
												default: CurrentOptions.SoundModel = SoundsBase.SoundModels.Inverse; break;
											}
											break;
										case "range":
											switch (Value.ToLowerInvariant())
											{
												case "low": CurrentOptions.SoundRange = SoundsBase.SoundRange.Low; break;
												case "medium": CurrentOptions.SoundRange = SoundsBase.SoundRange.Medium; break;
												case "high": CurrentOptions.SoundRange = SoundsBase.SoundRange.High; break;
												default: CurrentOptions.SoundRange = SoundsBase.SoundRange.Low; break;
											}
											break;
										case "number":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												CurrentOptions.SoundNumber = a < 16 ? 16 : a;
											}
											break;
									}
									break;
								case "verbosity":
									switch (Key)
									{
										case "showwarningmessages":
											CurrentOptions.ShowWarningMessages = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "showerrormessages":
											CurrentOptions.ShowErrorMessages = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "debuglog":
											Program.GenerateDebugLogging = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
									}
									break;
								case "folders":
									switch (Key)
									{
										case "route":
											CurrentOptions.RouteFolder = Value;
											break;
										case "train":
											CurrentOptions.TrainFolder = Value;
											break;
									}
									break;
								case "proxy":
									switch (Key)
									{
										case "url":
											CurrentOptions.ProxyUrl = Value;
											break;
										case "username":
											CurrentOptions.ProxyUserName = Value;
											break;
										case "password":
											CurrentOptions.ProxyPassword = Value;
											break;
									}
									break;
								case "packages":
									switch (Key)
									{
										case "compression":
											switch (Value.ToLowerInvariant())
											{
												case "zip":
													CurrentOptions.packageCompressionType = CompressionType.Zip;
													break;
												case "bzip":
													CurrentOptions.packageCompressionType = CompressionType.BZ2;
													break;
												case "gzip":
													CurrentOptions.packageCompressionType = CompressionType.TarGZ;
													break;
											}
											break;
									}
									break;
								case "recentlyusedroutes":
									{
										int n = CurrentOptions.RecentlyUsedRoutes.Length;
										Array.Resize(ref CurrentOptions.RecentlyUsedRoutes, n + 1);
										CurrentOptions.RecentlyUsedRoutes[n] = Value;
									}
									break;
								case "recentlyusedtrains":
									{
										int n = CurrentOptions.RecentlyUsedTrains.Length;
										Array.Resize(ref CurrentOptions.RecentlyUsedTrains, n + 1);
										CurrentOptions.RecentlyUsedTrains[n] = Value;
									}
									break;
								case "routeencodings":
									{
										int a;
										if (!int.TryParse(Key, NumberStyles.Integer, Culture, out a))
										{
											a = Encoding.UTF8.CodePage;
										}
										try
										{
#pragma warning disable CS0219
											//Used to check that the parsed integer is a valid codepage
											// ReSharper disable once UnusedVariable
											Encoding e = Encoding.GetEncoding(a);
#pragma warning restore CS0219
										}
										catch
										{
											a = Encoding.UTF8.CodePage;
										}
										int n = CurrentOptions.RouteEncodings.Length;
										Array.Resize(ref CurrentOptions.RouteEncodings, n + 1);
										CurrentOptions.RouteEncodings[n].Codepage = a;
										CurrentOptions.RouteEncodings[n].Value = Value;
									}
									break;
								case "trainencodings":
									{
										int a;
										if (!int.TryParse(Key, NumberStyles.Integer, Culture, out a))
										{
											a = Encoding.UTF8.CodePage;
										}
										try
										{
#pragma warning disable CS0219
											//Used to check that the parsed integer is a valid codepage
											// ReSharper disable once UnusedVariable
											Encoding e = Encoding.GetEncoding(a);
#pragma warning restore CS0219
										}
										catch
										{
											a = Encoding.UTF8.CodePage;
										}
										int n = CurrentOptions.TrainEncodings.Length;
										Array.Resize(ref CurrentOptions.TrainEncodings, n + 1);
										CurrentOptions.TrainEncodings[n].Codepage = a;
										CurrentOptions.TrainEncodings[n].Value = Value;
									}
									break;
								case "enableinputdeviceplugins":
									{
										int n = CurrentOptions.EnableInputDevicePlugins.Length;
										Array.Resize(ref CurrentOptions.EnableInputDevicePlugins, n + 1);
										CurrentOptions.EnableInputDevicePlugins[n] = Value;
									}
									break;
								case "parsers":
									switch (Key)
									{
										case "xobject":
											{
												int p;
												if (!int.TryParse(Value, NumberStyles.Integer, Culture, out p) || p < 0 || p > 3)
												{
													CurrentOptions.CurrentXParser = XParsers.Original;
												}
												else
												{
													CurrentOptions.CurrentXParser = (XParsers)p;
												}
												break;
											}
										case "objobject":
											{
												int p;
												if (!int.TryParse(Value, NumberStyles.Integer, Culture, out p) || p < 0 || p > 2)
												{
													CurrentOptions.CurrentObjParser = ObjParsers.Original;
												}
												else
												{
													CurrentOptions.CurrentObjParser = (ObjParsers)p;
												}
												break;
											}
									}
									break;
								case "touch":
									switch (Key)
									{
										case "cursor":
											CurrentOptions.CursorFileName = Value;
											break;
										case "panel2extended":
											CurrentOptions.Panel2ExtendedMode = string.Compare(Value, "false", StringComparison.OrdinalIgnoreCase) != 0;
											break;
										case "panel2extendedminsize":
											{
												int a;
												int.TryParse(Value, NumberStyles.Integer, Culture, out a);
												CurrentOptions.Panel2ExtendedMinSize = a;
											}
											break;
									}
									break;
							}
						}
					}
				}
			}
			else
			{
				// file not found
				string Code = CultureInfo.CurrentUICulture.Name;
				if (string.IsNullOrEmpty(Code))
				{
					Code = "en-US";
				}

				File = Path.CombineFile(Program.FileSystem.GetDataFolder("Languages"), Code + ".cfg");
				if (System.IO.File.Exists(File))
				{
					CurrentOptions.LanguageCode = Code;
				}
				else
				{
					try
					{
						int i = Code.IndexOf("-", StringComparison.Ordinal);
						if (i > 0)
						{
							Code = Code.Substring(0, i);
							File = Path.CombineFile(Program.FileSystem.GetDataFolder("Languages"), Code + ".cfg");
							if (System.IO.File.Exists(File))
							{
								CurrentOptions.LanguageCode = Code;
							}
						}
					}
					catch
					{
						CurrentOptions.LanguageCode = "en-US";
					}
				}
			}
		}
		internal static void SaveOptions()
		{
			CultureInfo Culture = CultureInfo.InvariantCulture;
			StringBuilder Builder = new StringBuilder();
			Builder.AppendLine("; Options");
			Builder.AppendLine("; =======");
			Builder.AppendLine("; This file was automatically generated. Please modify only if you know what you're doing.");
			Builder.AppendLine();
			Builder.AppendLine("[language]");
			Builder.AppendLine("code = " + CurrentOptions.LanguageCode);
			Builder.AppendLine();
			Builder.AppendLine("[interface]");
			Builder.AppendLine("folder = " + CurrentOptions.UserInterfaceFolder);
			{
				string t; switch (CurrentOptions.TimeTableStyle)
				{
					case TimeTableMode.None: t = "none"; break;
					case TimeTableMode.Default: t = "default"; break;
					case TimeTableMode.AutoGenerated: t = "autogenerated"; break;
					case TimeTableMode.PreferCustom: t = "prefercustom"; break;
					default: t = "default"; break;
				}
				Builder.AppendLine("timetablemode = " + t);
			}
			Builder.AppendLine("kioskMode = " + (CurrentOptions.KioskMode ? "true" : "false"));
			Builder.AppendLine("kioskModeTimer = " + CurrentOptions.KioskModeTimer);
			Builder.AppendLine();
			Builder.AppendLine("[display]");
			Builder.AppendLine("preferNativeBackend = " + (CurrentOptions.PreferNativeBackend ? "true" : "false"));
			Builder.AppendLine("mode = " + (CurrentOptions.FullscreenMode ? "fullscreen" : "window"));
			Builder.AppendLine("vsync = " + (CurrentOptions.VerticalSynchronization ? "true" : "false"));
			Builder.AppendLine("windowWidth = " + CurrentOptions.WindowWidth.ToString(Culture));
			Builder.AppendLine("windowHeight = " + CurrentOptions.WindowHeight.ToString(Culture));
			Builder.AppendLine("fullscreenWidth = " + CurrentOptions.FullscreenWidth.ToString(Culture));
			Builder.AppendLine("fullscreenHeight = " + CurrentOptions.FullscreenHeight.ToString(Culture));
			Builder.AppendLine("fullscreenBits = " + CurrentOptions.FullscreenBits.ToString(Culture));
			Builder.AppendLine("mainmenuWidth = " + CurrentOptions.MainMenuWidth.ToString(Culture));
			Builder.AppendLine("mainmenuHeight = " + CurrentOptions.MainMenuHeight.ToString(Culture));
			Builder.AppendLine("disableDisplayLists = " + (CurrentOptions.DisableDisplayLists ? "true" : "false"));
			Builder.AppendLine("loadInAdvance = " + (CurrentOptions.LoadInAdvance ? "true" : "false"));
			Builder.AppendLine("unloadtextures = " + (CurrentOptions.UnloadUnusedTextures ? "true" : "false"));
			Builder.AppendLine();
			Builder.AppendLine("[quality]");
			{
				string t; switch (CurrentOptions.Interpolation)
				{
					case InterpolationMode.NearestNeighbor: t = "nearestNeighbor"; break;
					case InterpolationMode.Bilinear: t = "bilinear"; break;
					case InterpolationMode.NearestNeighborMipmapped: t = "nearestNeighborMipmapped"; break;
					case InterpolationMode.BilinearMipmapped: t = "bilinearMipmapped"; break;
					case InterpolationMode.TrilinearMipmapped: t = "trilinearMipmapped"; break;
					case InterpolationMode.AnisotropicFiltering: t = "anisotropicFiltering"; break;
					default: t = "bilinearMipmapped"; break;
				}
				Builder.AppendLine("interpolation = " + t);
			}
			Builder.AppendLine("anisotropicFilteringLevel = " + CurrentOptions.AnisotropicFilteringLevel.ToString(Culture));
			Builder.AppendLine("anisotropicFilteringMaximum = " + CurrentOptions.AnisotropicFilteringMaximum.ToString(Culture));
			Builder.AppendLine("antiAliasingLevel = " + CurrentOptions.AntiAliasingLevel.ToString(Culture));
			Builder.AppendLine("transparencyMode = " + ((int)CurrentOptions.TransparencyMode).ToString(Culture));
			Builder.AppendLine("oldtransparencymode = " + (CurrentOptions.OldTransparencyMode ? "true" : "false"));
			Builder.AppendLine("viewingDistance = " + CurrentOptions.ViewingDistance.ToString(Culture));
			{
				string t; switch (CurrentOptions.MotionBlur)
				{
					case MotionBlurMode.Low: t = "low"; break;
					case MotionBlurMode.Medium: t = "medium"; break;
					case MotionBlurMode.High: t = "high"; break;
					default: t = "none"; break;
				}
				Builder.AppendLine("motionBlur = " + t);
			}
			Builder.AppendLine();
			Builder.AppendLine("[objectOptimization]");
			Builder.AppendLine("basicThreshold = " + CurrentOptions.ObjectOptimizationBasicThreshold.ToString(Culture));
			Builder.AppendLine("fullThreshold = " + CurrentOptions.ObjectOptimizationFullThreshold.ToString(Culture));
			Builder.AppendLine("vertexCulling = " + CurrentOptions.ObjectOptimizationVertexCulling.ToString(Culture));
			Builder.AppendLine();
			Builder.AppendLine("[simulation]");
			Builder.AppendLine("toppling = " + (CurrentOptions.Toppling ? "true" : "false"));
			Builder.AppendLine("collisions = " + (CurrentOptions.Collisions ? "true" : "false"));
			Builder.AppendLine("derailments = " + (CurrentOptions.Derailments ? "true" : "false"));
			Builder.AppendLine("loadingsway = " + (CurrentOptions.LoadingSway ? "true" : "false"));
			Builder.AppendLine("blackbox = " + (CurrentOptions.BlackBox ? "true" : "false"));
			Builder.Append("mode = ");
			switch (CurrentOptions.GameMode)
			{
				case GameMode.Arcade: Builder.AppendLine("arcade"); break;
				case GameMode.Normal: Builder.AppendLine("normal"); break;
				case GameMode.Expert: Builder.AppendLine("expert"); break;
				default: Builder.AppendLine("normal"); break;
			}
			Builder.AppendLine("acceleratedtimefactor = " + CurrentOptions.TimeAccelerationFactor);
			Builder.AppendLine("enablebvetshacks = " + (CurrentOptions.EnableBveTsHacks ? "true" : "false"));
			Builder.AppendLine();
			Builder.AppendLine("[verbosity]");
			Builder.AppendLine("showWarningMessages = " + (CurrentOptions.ShowWarningMessages ? "true" : "false"));
			Builder.AppendLine("showErrorMessages = " + (CurrentOptions.ShowErrorMessages ? "true" : "false"));
			Builder.AppendLine("debugLog = " + (Program.GenerateDebugLogging ? "true" : "false"));
			Builder.AppendLine();
			Builder.AppendLine("[controls]");
			Builder.AppendLine("useJoysticks = " + (CurrentOptions.UseJoysticks ? "true" : "false"));
			Builder.AppendLine("joystickAxisEB = " + (CurrentOptions.AllowAxisEB ? "true" : "false"));
			Builder.AppendLine("joystickAxisthreshold = " + CurrentOptions.JoystickAxisThreshold.ToString(Culture));
			Builder.AppendLine("keyRepeatDelay = " + (1000.0 * CurrentOptions.KeyRepeatDelay).ToString("0", Culture));
			Builder.AppendLine("keyRepeatInterval = " + (1000.0 * CurrentOptions.KeyRepeatInterval).ToString("0", Culture));
			Builder.AppendLine("raildrivermph = " + (CurrentOptions.RailDriverMPH ? "true" : "false"));
			Builder.AppendLine();
			Builder.AppendLine("[sound]");
			Builder.Append("model = ");
			switch (CurrentOptions.SoundModel)
			{
				case SoundsBase.SoundModels.Linear: Builder.AppendLine("linear"); break;
				default: Builder.AppendLine("inverse"); break;
			}
			Builder.Append("range = ");
			switch (CurrentOptions.SoundRange)
			{
				case SoundsBase.SoundRange.Low: Builder.AppendLine("low"); break;
				case SoundsBase.SoundRange.Medium: Builder.AppendLine("medium"); break;
				case SoundsBase.SoundRange.High: Builder.AppendLine("high"); break;
				default: Builder.AppendLine("low"); break;
			}
			Builder.AppendLine("number = " + CurrentOptions.SoundNumber.ToString(Culture));
			Builder.AppendLine();
			Builder.AppendLine("[proxy]");
			Builder.AppendLine("url = " + CurrentOptions.ProxyUrl);
			Builder.AppendLine("username = " + CurrentOptions.ProxyUserName);
			Builder.AppendLine("password = " + CurrentOptions.ProxyPassword);
			Builder.AppendLine();
			Builder.AppendLine("[packages]");
			Builder.Append("compression = ");
			switch (CurrentOptions.packageCompressionType)
			{
				case CompressionType.Zip: Builder.AppendLine("zip"); break;
				case CompressionType.TarGZ: Builder.AppendLine("gzip"); break;
				case CompressionType.BZ2: Builder.AppendLine("bzip"); break;
				default: Builder.AppendLine("zip"); break;
			}
			Builder.AppendLine();
			Builder.AppendLine("[folders]");
			Builder.AppendLine("route = " + CurrentOptions.RouteFolder);
			Builder.AppendLine("train = " + CurrentOptions.TrainFolder);
			Builder.AppendLine();
			Builder.AppendLine("[recentlyUsedRoutes]");
			for (int i = 0; i < CurrentOptions.RecentlyUsedRoutes.Length; i++)
			{
				Builder.AppendLine(CurrentOptions.RecentlyUsedRoutes[i]);
			}
			Builder.AppendLine();
			Builder.AppendLine("[recentlyUsedTrains]");
			for (int i = 0; i < CurrentOptions.RecentlyUsedTrains.Length; i++)
			{
				Builder.AppendLine(CurrentOptions.RecentlyUsedTrains[i]);
			}
			Builder.AppendLine();
			Builder.AppendLine("[routeEncodings]");
			for (int i = 0; i < CurrentOptions.RouteEncodings.Length; i++)
			{
				Builder.AppendLine(CurrentOptions.RouteEncodings[i].Codepage.ToString(Culture) + " = " + CurrentOptions.RouteEncodings[i].Value);
			}
			Builder.AppendLine();
			Builder.AppendLine("[trainEncodings]");
			for (int i = 0; i < CurrentOptions.TrainEncodings.Length; i++)
			{
				Builder.AppendLine(CurrentOptions.TrainEncodings[i].Codepage.ToString(Culture) + " = " + CurrentOptions.TrainEncodings[i].Value);
			}
			Builder.AppendLine();
			Builder.AppendLine("[enableInputDevicePlugins]");
			for (int i = 0; i < CurrentOptions.EnableInputDevicePlugins.Length; i++)
			{
				Builder.AppendLine(CurrentOptions.EnableInputDevicePlugins[i]);
			}
			Builder.AppendLine();
			Builder.AppendLine("[Parsers]");
			Builder.AppendLine("xObject = " + (int)CurrentOptions.CurrentXParser);
			Builder.AppendLine("objObject = " + (int)CurrentOptions.CurrentObjParser);
			Builder.AppendLine();
			Builder.AppendLine("[Touch]");
			Builder.AppendLine("cursor = " + CurrentOptions.CursorFileName);
			Builder.AppendLine("panel2extended = " + (CurrentOptions.Panel2ExtendedMode ? "true" : "false"));
			Builder.AppendLine("panel2extendedminsize = " + CurrentOptions.Panel2ExtendedMinSize.ToString(Culture));
			string File = Path.CombineFile(Program.FileSystem.SettingsFolder, "1.5.0/options.cfg");
			System.IO.File.WriteAllText(File, Builder.ToString(), new UTF8Encoding(true));
		}
	}
}
