 //1,4,11,2160
 //
 // 
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
 
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("openBVE")]
[assembly: AssemblyProduct("openBVE")]
[assembly: AssemblyCopyright("The openBVE Project")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.4.11.1376")]
[assembly: AssemblyFileVersion("1.4.11.1376")]
[assembly: CLSCompliant(true)]

namespace OpenBve {
	internal static partial class Program {
		internal const bool IsDevelopmentVersion = false;
		internal const string VersionSuffix = "";
	}
}
