// ReSharper disable UnusedMember.Global
// ReSharper disable InconsistentNaming
namespace Train.OpenBve
{
	/// <summary>Keys found in the Panel.cfg file</summary>
	internal enum PanelKey
	{
		Unknown = 0,
		Background = 1,
		背景 = 1,
		Yaw = 2,
		Pitch = 3,
		Type = 4,
		形態 = 4,
		Needle = 5,
		Hand = 5,
		針 = 5,
		LowerNeedle = 6,
		LowerHand = 6,
		下針 = 6,
		UpperNeedle = 7,
		UpperHand = 7,
		上針 = 7,
		Center = 8,
		中心 = 8,
		Radius = 9,
		半径 = 9,
		Cover = 10,
		ふた = 10,
		Unit = 11,
		単位 = 11,
		Maximum = 12,
		最大 = 12,
		Minimum = 13,
		最小 = 13,
		Angle = 14,
		角度 = 14,
		ATC = 15,
		ATCRadius = 16,
		ATC半径 = 16,
		Number = 17,
		数字 = 17,
		Corner = 18,
		左上 = 18,
		Size = 19,
		TurnOn = 20,
		点灯 = 20,
		TurnOff = 21,
		消灯 = 21,
		Image = 22,
		画像 = 22,
		Width = 23,
		幅 = 23,
	}
}
