namespace TrainManager.Car
{
	/// <summary>Contains the physics related properties for the car</summary>
	public class CarPhysics
	{
		/// <summary>Stores whether the car is a motor car</summary>
		public bool IsMotorCar;
		/// <summary>The current percieved speed of the car</summary>
		/// <remarks>Appears as if on a speedometer, accounting for wheel lock etc.</remarks>
		public double PerceivedSpeed;
		/// <summary>The current total acceleration output supplied by the car from all sources</summary>
		/// <remarks>Is positive for power and negative for brake, regardless of the train's direction</remarks>
		public double Acceleration;
		/// <summary>The acceleration generated by the motor</summary>
		/// <remarks>Is positive for power and negative for brake, regardless of the train's direction</remarks>
		public double MotorAcceleration;
		/// <summary>The body roll / shake direction</summary>
		public double RollShakeDirection;
		/// <summary>The amount of roll in radians applied due to toppling</summary>
		public double RollDueToTopplingAngle;
		/// <summary>The amount of roll in radians applied due to the cant of the track</summary>
		public double RollDueToCantAngle;
		/// <summary>The amount of roll in radians applied due to shaking of the train</summary>
		public double RollDueToShakingAngle;
		/// <summary>The angular speed of the roll applied due to shaking of the train</summary>
		public double RollDueToShakingAngularSpeed;
	}
}
