//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenBveApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenBveApi.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CoreFX {
            get {
                return ResourceManager.GetString("CoreFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2018 oleg-shilo
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above cop [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CS_Script {
            get {
                return ResourceManager.GetString("CS_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2019, F81 tec200
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without
        ///modification, are permitted provided that the following conditions are met: 
        ///
        ///1. Redistributions of source code must retain the above copyright notice,
        ///   this list of conditions and the following disclaimer. 
        ///2. Redistributions in binary form must reproduce the above copyright notice,
        ///   this list of conditions and the following disclaimer in the documentation
        ///   and/or other ma [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Cursors {
            get {
                return ResourceManager.GetString("Cursors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Licenses that apply to the DotNetZip library and tools
        ///
        ///As DotNetZip includes work derived from other projects, you are required to comply with the terms and conditions for each of them. These licenses include BSD, Apache, and zlib.
        ///
        ///To use the software, you must accept the licenses. If you do not accept the licenses, do not use the software.
        ///
        ///Original intellectual property in DotNetZip is provided under the Ms-PL:
        ///    
        ///    Copyright (c) 2006 - 2011 Dino Chiesa 
        ///    Copyright (c) 2006, 200 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DotNetZip {
            get {
                return ResourceManager.GetString("DotNetZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xliff version=&quot;1.2&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2.xsd&quot; xmlns=&quot;urn:oasis:names:tc:xliff:document:1.2&quot;&gt;
        ///	&lt;file datatype=&quot;plaintext&quot; original=&quot;en-US.xlf&quot; source-language=&quot;en-US&quot;&gt;
        ///		&lt;body&gt;
        ///			&lt;group id=&quot;language&quot;&gt;
        ///				&lt;trans-unit id=&quot;name&quot;&gt;
        ///					&lt;source&gt;English (United States)&lt;/source&gt;
        ///				&lt;/trans-unit&gt;
        ///				&lt;trans-unit id=&quot;flag&quot;&gt;
        ///					&lt;source&gt;US.png&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///
        ///A &quot;contributor&quot; is any person that distributes its contribution [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NAudio {
            get {
                return ResourceManager.GetString("NAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2015 Andrew Ward, Ms-PL
        ///
        ///Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///A &quot;contributor&quot; is any person t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NAudio_Vorbis {
            get {
                return ResourceManager.GetString("NAudio_Vorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License
        ///
        ///Copyright (c) 2018 Mark Heath, Andrew Ward &amp; Contributors
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NLayer {
            get {
                return ResourceManager.GetString("NLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2015 Andrew Ward, Ms-PL
        ///
        ///Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///A &quot;contributor&quot; is any person t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NVorbis {
            get {
                return ResourceManager.GetString("NVorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Open Toolkit library license
        ///
        ///Copyright (c) 2006 - 2014 Stefanos Apostolopoulos &lt;stapostol@gmail.com&gt; for the Open Toolkit library.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Softwar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OpenTK {
            get {
                return ResourceManager.GetString("OpenTK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation
        ///
        ///All rights reserved. Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Prism {
            get {
                return ResourceManager.GetString("Prism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) .NET Foundation and Contributors
        ///All Rights Reserved
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you
        ///may not use this file except in compliance with the License. You may
        ///obtain a copy of the License at
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
        ///implied. See the Lic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReactiveExtensions {
            get {
                return ResourceManager.GetString("ReactiveExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2018 neuecc, xin9le, okazuki
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReactiveProperty {
            get {
                return ResourceManager.GetString("ReactiveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanYing Input is a cross-ported copy of the BVE5 input plugin by Rock_On, used to support the OHC-PC01
        ///desktop cab controller.
        ///
        ///The original BVE5 repository / source code may be found at the following address:
        ///https://bitbucket.org/mikangogo/sanyinginput
        ///
        ///
        ///The MIT License (MIT)
        ///
        ///Copyright (c) 2017 Rock_On, 2018 The openBVE Project
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///the Sof [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SanYing_Input {
            get {
                return ResourceManager.GetString("SanYing_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2014  Adam Hathcock
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SharpCompress {
            get {
                return ResourceManager.GetString("SharpCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2019, F81 tec200
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without
        ///modification, are permitted provided that the following conditions are met: 
        ///
        ///1. Redistributions of source code must retain the above copyright notice,
        ///   this list of conditions and the following disclaimer. 
        ///2. Redistributions in binary form must reproduce the above copyright notice,
        ///   this list of conditions and the following disclaimer in the documentation
        ///   and/or other ma [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TrainEditor2_Icons {
            get {
                return ResourceManager.GetString("TrainEditor2_Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                           MOZILLA PUBLIC LICENSE
        ///                                Version 1.1
        ///
        ///                              ---------------
        ///
        ///1. Definitions.
        ///
        ///     1.0.1. &quot;Commercial Use&quot; means distribution or otherwise making the
        ///     Covered Code available to a third party.
        ///
        ///     1.1. &quot;Contributor&quot; means each entity that creates or contributes to
        ///     the creation of Modifications.
        ///
        ///     1.2. &quot;Contributor Version&quot; means the combination of the Original
        ///     Code, prior Modifications used by a  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ude {
            get {
                return ResourceManager.GetString("Ude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2015 Microsoft
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XamlBehaviorsForWPF {
            get {
                return ResourceManager.GetString("XamlBehaviorsForWPF", resourceCulture);
            }
        }
    }
}
