.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OPENBVE-OBJECTVIEWER 6 "5 April 2009" openBVE Object Viewer
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH "NAME"
openBVE Object Viewer \- Development tool for openBVE

.br
.SH "DESCRIPTION"
Object Viewer is a development tool for openBVE.

It enables you to view a single 3D model in any of the supported object formats.

.br
.SH "AUTHOR"
.TP
OpenBVE was written by Michelle Boucquemont <reschanger@gmail.com> and placed in the public domain.
.TP
This manual page was written for Debian/Ubuntu by Paul Sladen <ubuntu@paul.sladen.org>

.br
.SH "SEE ALSO"
Website:
.BR http://trainsimframework.org/
.br

