namespace LibRender2.Overlays
{
	/// <summary>Defines the possible timetable display modes</summary>
	public enum TimeTableMode
	{
		/// <summary>Timetable display is disabled</summary>
		None = 0,
		/// <summary>The custom timetable (if set) will be displayed first, followed by the auto-generated timetable</summary>
		Default = 1,
		/// <summary>Only the auto-generated timetable will be displayed</summary>
		AutoGenerated = 2,
		/// <summary>The auto-generated timetable will be displayed only if no custom timetable is available</summary>
		PreferCustom = 3
	}
}
