//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenBveApi.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Licenses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Licenses() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenBveApi.Resources.Licenses", typeof(Licenses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AssimpParser is a cross-ported copy of Open Asset Import Library (assimp) by assimp team.
        ///
        ///The original repository / source code may be found at the following address:
        ///https://github.com/assimp/assimp
        ///
        ///
        ///Open Asset Import Library (assimp)
        ///
        ///Copyright (c) 2006-2016, assimp team, 2018, The openBVE Project
        ///All rights reserved.
        ///
        ///Redistribution and use of this software in source and binary forms,
        ///with or without modification, are permitted provided that the
        ///following conditions are met:
        ///
        ///* Redistrib [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssimpParser {
            get {
                return ResourceManager.GetString("AssimpParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License (MIT)
        ///
        ///Copyright (c) 2018 oleg-shilo
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above cop [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CS_Script {
            get {
                return ResourceManager.GetString("CS_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (c) 2019, F81 tec200
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without
        ///modification, are permitted provided that the following conditions are met: 
        ///
        ///1. Redistributions of source code must retain the above copyright notice,
        ///   this list of conditions and the following disclaimer. 
        ///2. Redistributions in binary form must reproduce the above copyright notice,
        ///   this list of conditions and the following disclaimer in the documentation
        ///   and/or other ma [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cursors {
            get {
                return ResourceManager.GetString("Cursors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to t [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string dotnet_runtime {
            get {
                return ResourceManager.GetString("dotnet_runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Software Licenses that apply to the DotNetZip library and tools
        ///
        ///As DotNetZip includes work derived from other projects, you are required to comply with the terms and conditions for each of them. These licenses include BSD, Apache, and zlib.
        ///
        ///To use the software, you must accept the licenses. If you do not accept the licenses, do not use the software.
        ///
        ///Original intellectual property in DotNetZip is provided under the Ms-PL:
        ///    
        ///    Copyright (c) 2006 - 2011 Dino Chiesa 
        ///    Copyright (c) 2006, 200 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DotNetZip {
            get {
                return ResourceManager.GetString("DotNetZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIT License
        ///
        ///Copyright (c) 2019 Rico Suter
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice a [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Namotion_Reflection {
            get {
                return ResourceManager.GetString("Namotion_Reflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///
        ///A &quot;contributor&quot; is any person that distributes its contribution [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NAudio {
            get {
                return ResourceManager.GetString("NAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (c) 2015 Andrew Ward, Ms-PL
        ///
        ///Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///A &quot;contributor&quot; is any person t [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NAudio_Vorbis {
            get {
                return ResourceManager.GetString("NAudio_Vorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License (MIT)
        ///
        ///Copyright (c) 2007 James Newton-King
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above c [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Newtonsoft_Json {
            get {
                return ResourceManager.GetString("Newtonsoft_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License (MIT)
        ///
        ///Copyright (c) 2016 Rico Suter
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyrigh [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NJsonSchema {
            get {
                return ResourceManager.GetString("NJsonSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIT License
        ///
        ///Copyright (c) 2018 Mark Heath, Andrew Ward &amp; Contributors
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NLayer {
            get {
                return ResourceManager.GetString("NLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (c) 2015 Andrew Ward, Ms-PL
        ///
        ///Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///A &quot;contributor&quot; is any person t [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NVorbis {
            get {
                return ResourceManager.GetString("NVorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///                     GNU LIBRARY GENERAL PUBLIC LICENSE
        ///                       Version 2, June 1991
        ///
        /// Copyright (C) 1991 Free Software Foundation, Inc.
        /// 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///[This is the first released version of the library GPL.  It is
        /// numbered 2 because it goes with version 2 of the ordinary GPL.]
        ///
        ///                            Preamble
        ///        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenALSoft {
            get {
                return ResourceManager.GetString("OpenALSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Open Toolkit library license
        ///
        ///Copyright (c) 2006 - 2014 Stefanos Apostolopoulos &lt;stapostol@gmail.com&gt; for the Open Toolkit library.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Softwar [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenTK {
            get {
                return ResourceManager.GetString("OpenTK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation
        ///
        ///All rights reserved. Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prism {
            get {
                return ResourceManager.GetString("Prism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (c) .NET Foundation and Contributors
        ///All Rights Reserved
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you
        ///may not use this file except in compliance with the License. You may
        ///obtain a copy of the License at
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
        ///implied. See the Lic [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReactiveExtensions {
            get {
                return ResourceManager.GetString("ReactiveExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License (MIT)
        ///
        ///Copyright (c) 2018 neuecc, xin9le, okazuki
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReactiveProperty {
            get {
                return ResourceManager.GetString("ReactiveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SanYing Input is a cross-ported copy of the BVE5 input plugin by Rock_On, used to support the OHC-PC01
        ///desktop cab controller.
        ///
        ///The original BVE5 repository / source code may be found at the following address:
        ///https://bitbucket.org/mikangogo/sanyinginput
        ///
        ///
        ///The MIT License (MIT)
        ///
        ///Copyright (c) 2017 Rock_On, 2018 The openBVE Project
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///the Sof [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SanYing_Input {
            get {
                return ResourceManager.GetString("SanYing_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License (MIT)
        ///
        ///Copyright (c) 2014  Adam Hathcock
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SharpCompress {
            get {
                return ResourceManager.GetString("SharpCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (c) 2019, F81 tec200
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without
        ///modification, are permitted provided that the following conditions are met: 
        ///
        ///1. Redistributions of source code must retain the above copyright notice,
        ///   this list of conditions and the following disclaimer. 
        ///2. Redistributions in binary form must reproduce the above copyright notice,
        ///   this list of conditions and the following disclaimer in the documentation
        ///   and/or other ma [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrainEditor2_Icons {
            get {
                return ResourceManager.GetString("TrainEditor2_Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///                             MOZILLA PUBLIC LICENSE
        ///                                Version 1.1
        ///
        ///                              ---------------
        ///
        ///1. Definitions.
        ///
        ///     1.0.1. &quot;Commercial Use&quot; means distribution or otherwise making the
        ///     Covered Code available to a third party.
        ///
        ///     1.1. &quot;Contributor&quot; means each entity that creates or contributes to
        ///     the creation of Modifications.
        ///
        ///     1.2. &quot;Contributor Version&quot; means the combination of the Original
        ///     Code, prior Modifications used by a  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ude {
            get {
                return ResourceManager.GetString("Ude", resourceCulture);
            }
        }
    }
}
